import type { Config } from "tailwindcss";

const config: Config = {
    content: [
        "./app/**/*.{js,ts,jsx,tsx,mdx}",
        "./components/**/*.{js,ts,jsx,tsx,mdx}",
        "./lib/**/*.{js,ts,jsx,tsx,mdx}",
    ],
    darkMode: "class",
    theme: {
        extend: {
            colors: {
                "surface": "#fcf9f8",
                "primary-fixed": "#84f9b6",
                "inverse-on-surface": "#f3f0ef",
                "tertiary-fixed-dim": "#5dd4ff",
                "tertiary": "#006782",
                "surface-container": "#f0eded",
                "surface-container-lowest": "#ffffff",
                "background": "#fcf9f8",
                "on-tertiary-fixed-variant": "#004d62",
                "error-container": "#ffdad6",
                "on-tertiary-fixed": "#001f29",
                "on-primary-fixed-variant": "#005230",
                "on-secondary": "#ffffff",
                "on-primary-container": "#003e23",
                "on-secondary-fixed": "#001b3f",
                "surface-container-low": "#f6f3f2",
                "secondary-fixed": "#d7e3ff",
                "primary-fixed-dim": "#67dc9b",
                "on-error": "#ffffff",
                "on-primary-fixed": "#002110",
                "surface-container-highest": "#e5e2e1",
                "error": "#ba1a1a",
                "tertiary-fixed": "#baeaff",
                "surface-container-high": "#eae7e7",
                "on-surface": "#1c1b1b",
                "secondary": "#455f8c",
                "outline-variant": "#bdcabe",
                "tertiary-container": "#00abd6",
                "on-secondary-fixed-variant": "#2c4773",
                "secondary-container": "#b0cafe",
                "on-primary": "#ffffff",
                "inverse-primary": "#67dc9b",
                "on-tertiary-container": "#003a4b",
                "on-surface-variant": "#3e4a41",
                "primary-container": "#38b275",
                "on-secondary-container": "#3b5481",
                "surface-dim": "#dcd9d9",
                "secondary-fixed-dim": "#adc7fb",
                "on-background": "#1c1b1b",
                "primary": "#006d41",
                "surface-bright": "#fcf9f8",
                "outline": "#6d7a70",
                "on-error-container": "#93000a",
                "on-tertiary": "#ffffff",
                "surface-variant": "#e5e2e1",
                "surface-tint": "#006d41",
                "inverse-surface": "#313030",
                "jade-green": "#1d7f56",
                "berkeley-blue": "#1A3661"
            },
            fontFamily: {
                "headline": ["Plus Jakarta Sans", "sans-serif"],
                "body": ["Manrope", "sans-serif"],
            },
        },
    },
};
export default config;
